name: "$(Build.DefinitionName) #$(Build.BuildId)"

trigger: none # Manual Publish
pr: none # GitHub Actions handle PRs

parameters:
  - name: AgentPoolName
    displayName: Agent pool name
    type: string
    default: ADO Windows Server 2022

  - name: AgentName
    displayName: Agent name - single char for any
    type: string
    default: " "

  - name: NuGetVersion
    displayName: NuGet version
    type: string
    default: 3.0.1

  - name: ProductTfm
    displayName: Product Target Framework
    type: string
    default: net8.0

resources:
  repositories:
    - repository: self
      type: git

  containers:
    - container: Windows
      image: mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build and Pack

        pool:
          name: ${{ parameters.AgentPoolName }}
          ${{ if ne(length(parameters.AgentName), 1) }}:
            demands:
              - Agent.Name -equals ${{ parameters.AgentName }}
        container: Windows

        variables:
          - group: Code Sign KV Auth

          - name: Configuration
            value: Release

          - name: ProjectPath
            value: src/Kentico.Xperience.Disqus/Kentico.Xperience.Disqus.csproj

          # This parameter needs to be "re-saved" to variable
          # Usages of this variable must be in runtime format: $(NuGetVersion)
          - name: NuGetVersion
            value: ${{ parameters.NuGetVersion }}

          - name: ApiChangesConsoleFolder
            value: $(System.DefaultWorkingDirectory)/tool

          - name: ReleasedProjectFolder
            value: $(System.DefaultWorkingDirectory)/ReleasedProject
          - name: ReleasedDllsFolder
            value: $(ReleasedProjectFolder)/publish
          - name: ReleasedNugetsFolder
            value: $(ReleasedProjectFolder)/nugets

          - name: CurrentProjectFolder
            value: $(System.DefaultWorkingDirectory)/CurrentProject
          - name: CurrentDllsFolder
            value: $(CurrentProjectFolder)/publish
          - name: CurrentNugetsFolder
            value: $(CurrentProjectFolder)/nugets

        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore dotnet tools
            inputs:
              command: custom
              custom: tool
              arguments: restore
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: DotNetCoreCLI@2
            displayName: Restore dependencies
            inputs:
              command: restore
              projects: ${{ variables.ProjectPath }}
              feedsToUse: select
              restoreArguments: --locked-mode

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: ${{ variables.ProjectPath }}
              configuration: ${{ variables.Configuration }}
              arguments: --no-restore
            env:
              AuthenticodeClientSecret: $(AuthenticodeClientSecret)
              # Roll-forward behavior set for AzureSignTool dotnet tool (see .config\dotnet-tools.json) which requires .Net 6.0 runtime
              DOTNET_ROLL_FORWARD: Major

          - task: DotNetCoreCLI@2
            displayName: Create NuGet package
            inputs:
              command: pack
              packagesToPack: ${{ variables.ProjectPath }}
              configuration: ${{ variables.Configuration }}
              packDirectory: $(CurrentNugetsFolder)
              includesymbols: true
              nobuild: true
              versioningScheme: off

          # Download artifact from pipeline: [Tools] Api changes
          - task: DownloadPipelineArtifact@2
            displayName: Download Api Changes.Console
            inputs:
              buildType: specific
              project: CMS
              definition: "578"
              buildVersionToDownload: latestFromBranch
              branchName: refs/heads/master
              artifact: ApiChanges.Console
              path: $(System.ArtifactsDirectory)

          - pwsh: |
              $null = New-Item -Path '$(ReleasedProjectFolder)' -ItemType 'Directory'
              Set-Location -Path '$(ReleasedProjectFolder)'

              & dotnet new web -f ${{ parameters.ProductTfm }}

              foreach ($nuget in Get-ChildItem -Path '$(CurrentNugetsFolder)/*' -Include '*.nupkg') {
                  $nugetVersionStart = $nuget.BaseName.IndexOf('.$(NuGetVersion)')
                  $nugetName = $nuget.BaseName.Substring(0, $nugetVersionStart)

                  Write-Host "##[debug]Adding latest version of the NuGet package: $nugetName"
                  
                  & dotnet add package $nugetName --prerelease -s https://api.nuget.org/v3/index.json
              }

              & dotnet publish -o '$(ReleasedDllsFolder)' -c Release -r win-x64 --self-contained
            displayName: Get released Dlls
            env:
              AuthenticodeClientSecret: $(AuthenticodeClientSecret)
              # Roll-forward behavior set for AzureSignTool dotnet tool (see .config\dotnet-tools.json) which requires .Net 6.0 runtime
              DOTNET_ROLL_FORWARD: Major

          - pwsh: |
              & dotnet new web -f ${{ parameters.ProductTfm }}

              & dotnet new nugetconfig
              & dotnet nuget add source '$(CurrentNugetsFolder)' --name local

              $nugetConfigFilePath = Join-Path (Get-Location) "nuget.config"
              [xml]$xml = Get-Content $nugetConfigFilePath

              $packageSourceMapping = $xml.CreateElement("packageSourceMapping")
              $xml.configuration.AppendChild($packageSourceMapping) | Out-Null

              $packageSource = $xml.CreateElement("packageSource")
              $packageSource.SetAttribute("key", "local")

              $packageSourceMapping.AppendChild($packageSource) | Out-Null

              foreach ($nuget in Get-ChildItem -Path '$(CurrentNugetsFolder)/*' -Include '*.nupkg') {
                $nugetVersionStart = $nuget.BaseName.IndexOf('.$(NuGetVersion)')
                $nugetName = $nuget.BaseName.Substring(0, $nugetVersionStart)

                $package = $xml.CreateElement("package")
                $package.SetAttribute("pattern", $nugetName)

                $packageSource.AppendChild($package) | Out-Null
              }

              Set-Content -Path $nugetConfigFilePath -Value $xml.OuterXml

              foreach ($nuget in Get-ChildItem -Path '$(CurrentNugetsFolder)/*' -Include '*.nupkg') {
                $nugetVersionStart = $nuget.BaseName.IndexOf('.$(NuGetVersion)')
                $nugetName = $nuget.BaseName.Substring(0, $nugetVersionStart)

                Write-Host "##[debug]Adding version $(NuGetVersion) of the NuGet package: $nugetName"

                & dotnet add package $nugetName -v $(NuGetVersion)
              }

              & dotnet publish -o '$(CurrentDllsFolder)' -c Release -r win-x64 --self-contained
            displayName: Get current Dlls
            workingDirectory: $(CurrentProjectFolder)
            env:
              AuthenticodeClientSecret: $(AuthenticodeClientSecret)
              # Roll-forward behavior set for AzureSignTool dotnet tool (see .config\dotnet-tools.json) which requires .Net 6.0 runtime
              DOTNET_ROLL_FORWARD: Major

          - pwsh: |
              dotnet tool install --global Microsoft.DotNet.ApiCompat.Tool
              $releasedDllPath = Join-Path '$(ReleasedDllsFolder)' 'Kentico.Xperience.Disqus.dll'
              $currentDllPath = Join-Path '$(CurrentDllsFolder)' 'Kentico.Xperience.Disqus.dll'

              $output = apicompat --left $releasedDllPath --right $currentDllPath | Out-String

              # This is pretty naive
              if ($output -match "API compatibility errors") {
                Write-Error "API combat tool detected breaking changes."
                exit 1
              }
            displayName: Install & run API combat tool and fail on breaking changes

          - task: ExtractFiles@1
            displayName: Extract Api Changes tool
            inputs:
              archiveFilePatterns: $(System.ArtifactsDirectory)/ApiChanges.Console.zip
              destinationFolder: $(ApiChangesConsoleFolder)

          - pwsh: |
              $configPath = Join-Path $(ApiChangesConsoleFolder) "config.json"
              New-Item -Path $configPath -ItemType File -Force | Out-Null
              Set-Content -Path $configPath -Value '{ "Include": ["Kentico.Xperience.Disqus*.dll"], "Exclude": [], "Ignore": {} }'
            displayName: Create empty config.json file

          # - pwsh: >
          #     & $(BuildScriptsFolder)/Add-IgnoredApiChangesToConfigFile.ps1
          #     -ResolutionsFolder '$(ApiChangesConsoleFolder)/Resolutions'
          #     -SourcePath '$(ApiChangesConsoleFolder)/config.source.json'
          #     -TargetPath '$(ApiChangesConsoleFolder)/config.json'
          #   displayName: Generate API changes config file

          # - pwsh: >
          #     & $(BuildScriptsFolder)/Add-IgnoredApiChangesToConfigFile.ps1
          #     -ResolutionsFolder '$(ApiChangesConsoleFolder)/Resolutions/${{ parameters.ProductTfm }}'
          #     -SourcePath '$(ApiChangesConsoleFolder)/config.json'
          #     -TargetPath '$(ApiChangesConsoleFolder)/config.json'
          #   displayName: Add API changes related of specified dotnet version to config file

          - script: >
              $(ApiChangesConsoleFolder)/ApiChanges.Console.exe
              -s "$(ReleasedDllsFolder)"
              -t "$(CurrentDllsFolder)"
              -c "$(ApiChangesConsoleFolder)/config.json"
            displayName: Run Api Changes detection

          - task: PublishTestResults@2
            displayName: Publish Test Results **/TEST-*.xml
            condition: succeededOrFailed()
            inputs:
              testRunTitle: $(System.StageDisplayName)
              testResultsFormat: NUnit
              searchFolder: $(ApiChangesConsoleFolder)/
