//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.Disqus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class DisqusResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisqusResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kentico.Xperience.Disqus.Resources.DisqusResources", typeof(DisqusResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any number of CSS classes to apply to the Disqus thread, e.g. &apos;comments blue&apos;.
        /// </summary>
        internal static string admin_disqus_properties_cssclass_explanationText {
            get {
                return ResourceManager.GetString("admin.disqus.properties.cssclass.explanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Css classes.
        /// </summary>
        internal static string admin_disqus_properties_cssclass_label {
            get {
                return ResourceManager.GetString("admin.disqus.properties.cssclass.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether you want to add Disqus comment counts. You will need to add &apos;#disqus_thread&apos; to your article URLs. See Disqus documentation for this..
        /// </summary>
        internal static string admin_disqus_properties_displayCommentCount_explanationText {
            get {
                return ResourceManager.GetString("admin.disqus.properties.displayCommentCount.explanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display disqus comment count.
        /// </summary>
        internal static string admin_disqus_properties_displayCommentCount_label {
            get {
                return ResourceManager.GetString("admin.disqus.properties.displayCommentCount.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unique string identifying the current page. If empty, it will be generated based on the page&apos;s WebPageItemID..
        /// </summary>
        internal static string admin_disqus_properties_pageIdentifier_explanationText {
            get {
                return ResourceManager.GetString("admin.disqus.properties.pageIdentifier.explanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disqus page identifier.
        /// </summary>
        internal static string admin_disqus_properties_pageIdentifier_label {
            get {
                return ResourceManager.GetString("admin.disqus.properties.pageIdentifier.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A custom title for the created Disqus thread..
        /// </summary>
        internal static string admin_disqus_properties_title_explanationText {
            get {
                return ResourceManager.GetString("admin.disqus.properties.title.explanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disqus title.
        /// </summary>
        internal static string admin_disqus_properties_title_label {
            get {
                return ResourceManager.GetString("admin.disqus.properties.title.label", resourceCulture);
            }
        }
    }
}
